from .constance import (CREATE_PRAYER_TIMES_TABLE, EZANVAKTI_MAINZ_URL, CALENDAR_FILE, PRAYER_TIMES_DB,
                        INSERT_PRAYER_TIMES_TABLE, SELECT_PRAYER_TIMES_TABLE, SELECT_ALL_PRAYER_TIMES_TABLE,
                        IMAME)